on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
  Test:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - uses: actions/checkout@v2
      - name: Change Directory
        run: cd code_coverage
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
